name: 🛑 MAIN BRANCH SECURITY

on:
  pull_request:
    branches:
      - main

jobs:
  check_branch_and_repository:
    name: 🛑 Verify Source branch and repository
    runs-on: ubuntu-latest

    steps:
    - name: 🧾 Check out code
      uses: actions/checkout@v2

    - name: 🛑 Verify source branch and repository
      run: |
        if [[ "${{ github.event.pull_request.head.ref }}" =~ ^v.*\..*\..*-dev$ && "${{ github.event.repository }}" == "jnmprojects/noplus" ]]; then
          echo "Success: Pull request is from v*.*.*-dev branch and @jnmprojects/noplus repository."
        else
          echo "Error: Pull request must come from v*.*.*-dev branch and @jnmprojects/noplus repository."
          exit 1
        fi
