name: Local CI Scripts 🧾 for Web Branches ✔

on: workflow_dispatch

jobs:
  storybook:
    name: Storybook 📚
    runs-on: JnMP
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: pnpm i

      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: apps/Web App
          onlyChanged: true